version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432" 
    networks:
      - employee_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: python:3.12.10
    container_name: django_container
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - employee_network

networks:
  employee_network:
    driver: bridge

volumes:
  postgres_data:
