version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "3607:3306"
    networks:
      - employee_network
    command: --default-authentication-plugin=mysql_native_password

  web:
    image: python:3.12.10
    container_name: django_container
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - employee_network


networks:
  employee_network:
    driver: bridge


